### ISSUE TITLE
Inline equations rendering with MathJax

### ISSUE THREAD

**Issue by isomorphicdude** [zivong/ockham#1]
Hi, I really appreciate your work. However, there seems to be a minor issue when I try to render inline equations with the dollar signs `$$`. Would it be possible to add inline options for MathJax rendering? Thanks very much!

**Comment by zivong** [comment]
In fact, MathJax uses `\(...\)` as the default delimiters for inline math. So in Markdown, you can write an inline math equation, for example, `\\(e^{i\pi}+1=0\\)`.

But you can also configure the MathJax to use `$...$` as the default delimiters for inline math. Just put the following code into the `<head>`:

```html
<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  }
};
</script>
```

However, `\(...\)` is recommended.

> That is because dollar signs appear too often in non-mathematical settings, which could cause some text to be treated as mathematics unexpectedly. For example, with single-dollar delimiters, “… the cost is $2.50 for the first one, and $2.00 for each additional one …” would cause the phrase “2.50 for the first one, and” to be treated as mathematics since it falls between dollar signs.

**Comment by isomorphicdude** [comment]
Thanks very much! I solved this issue by following your instructions and added *mathjax.html* to the directory `_includes` with the code you provided and included `{% include mathjax.html %}` in *post.html*.  
Just to add a little bit of information: due to my extreme lack of knowledge, the code did not work for me first, but I later found out that it should be placed after `{% include custom-head.html %}`, then everything works. 
Thanks again and sorry for the hassle
